#ifndef COCOBOT_CONFIG_H
#define COCOBOT_CONFIG_H

#define COCOBOT_GS_UD_SHELL_CONFIGURATION 0

#define COCOBOT_INVERT_LEFT_MOTOR
#define COCOBOT_INVERT_RIGHT_MOTOR

#define COCOBOT_LOW_BAT_THRESHOLD 13500

#endif//COCOBOT_CONFIG_H
