#ifndef COCOBOT_CONFIG_H
#define COCOBOT_CONFIG_H

#define COCOBOT_CAN_MOTOR
#define COCOBOT_COM_NODE_ID 30
#define COCOBOT_RIGHT_MOTOR_NODE_ID 33
#define COCOBOT_LEFT_MOTOR_NODE_ID 32
#define COCOBOT_LIDAR_NODE_ID 34

#endif//COCOBOT_CONFIG_H
