#include "cocobot_pathfinder_config.h"
#include "cocobot.h"


const cocobot_pathfinder_table_init_s initTable [] = 
{
    //Walls
    {0, 0, TABLE_LENGTH_GRID, ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {0, TABLE_WIDTH_GRID - ROBOT_HALF_DIAG_GRID, TABLE_LENGTH_GRID, ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {0, 0, ROBOT_HALF_DIAG_GRID, TABLE_WIDTH_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {TABLE_LENGTH_GRID - ROBOT_HALF_DIAG_GRID, 0, ROBOT_HALF_DIAG_GRID, TABLE_WIDTH_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},

    //Construction zone
    {41 - ROBOT_HALF_DIAG_GRID, 0, 11 + ROBOT_HALF_DIAG_GRID, 4 + ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_NEG},
    {8, 0, 11 + ROBOT_HALF_DIAG_GRID, 4 + ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_POS},

    //Depart zone
    {52 - ROBOT_HALF_DIAG_GRID, 0, 8 + ROBOT_HALF_DIAG_GRID, 13 + ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_NEG},
    {0, 0, 8 + ROBOT_HALF_DIAG_GRID, 13 + ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_POS},

    //Epuration station
    {17, TABLE_WIDTH_GRID - 5 - ROBOT_HALF_DIAG_GRID, 26, 5 + ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {17 - ROBOT_HALF_DIAG_GRID, TABLE_WIDTH_GRID - 5, ROBOT_HALF_DIAG_GRID, 5, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {17, TABLE_WIDTH_GRID - 5, ROBOT_HALF_DIAG_GRID, 5, SOFT_OBSTACLE, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {43, TABLE_WIDTH_GRID - 5, ROBOT_HALF_DIAG_GRID, 5, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {43, TABLE_WIDTH_GRID - 5, ROBOT_HALF_DIAG_GRID, 0, SOFT_OBSTACLE, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},

    //Distributors
    {0, 16, 2 + ROBOT_HALF_DIAG_GRID, 2, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {0, 16 - ROBOT_HALF_DIAG_GRID, 2, ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {0, 16 + 2, 2, ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {0 + 1, 16 + 1, ROBOT_HALF_DIAG_GRID, 2, SOFT_OBSTACLE, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},

    {TABLE_LENGTH_GRID - 2 - ROBOT_HALF_DIAG_GRID, 16, 2 + ROBOT_HALF_DIAG_GRID, 2, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {TABLE_LENGTH_GRID - 2, 16 - ROBOT_HALF_DIAG_GRID, 2, ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {TABLE_LENGTH_GRID - 2, 16 + 2, 2, ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {TABLE_LENGTH_GRID - 1, 16 + 1, ROBOT_HALF_DIAG_GRID, 2, SOFT_OBSTACLE, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},

    {11, TABLE_WIDTH_GRID - 2 - ROBOT_HALF_DIAG_GRID, 2, 2 + ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {11 - ROBOT_HALF_DIAG_GRID, TABLE_WIDTH_GRID - 2, ROBOT_HALF_DIAG_GRID, 2, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {11 + 2, TABLE_WIDTH_GRID - 2, ROBOT_HALF_DIAG_GRID, 2, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {11 + 1, TABLE_WIDTH_GRID - 1, ROBOT_HALF_DIAG_GRID, 0, SOFT_OBSTACLE, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},

    {47, TABLE_WIDTH_GRID - 2 - ROBOT_HALF_DIAG_GRID, 2, 2 + ROBOT_HALF_DIAG_GRID, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {47 - ROBOT_HALF_DIAG_GRID, TABLE_WIDTH_GRID - 2, ROBOT_HALF_DIAG_GRID, 2, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {47 + 2, TABLE_WIDTH_GRID - 2, ROBOT_HALF_DIAG_GRID, 2, SOFT_OBSTACLE, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {47 + 1, TABLE_WIDTH_GRID - 1, ROBOT_HALF_DIAG_GRID, 0, SOFT_OBSTACLE, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    
    //Walls
    {0, 0, TABLE_LENGTH_GRID, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {0, TABLE_WIDTH_GRID - ROBOT_HALF_WIDTH_GRID, TABLE_LENGTH_GRID, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {0, 0, ROBOT_HALF_WIDTH_GRID, TABLE_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {TABLE_LENGTH_GRID - ROBOT_HALF_WIDTH_GRID, 0, ROBOT_HALF_WIDTH_GRID, TABLE_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},

    //Construction zone
    {41 - ROBOT_HALF_WIDTH_GRID, 0, 11 + ROBOT_HALF_WIDTH_GRID, 4 + ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_NEG},
    {8, 0, 11 + ROBOT_HALF_WIDTH_GRID, 4 + ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_POS},

    //Depart zone
    {52 - ROBOT_HALF_WIDTH_GRID, 0, 8 + ROBOT_HALF_WIDTH_GRID, 13 + ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_NEG},
    {0, 0, 8 + ROBOT_HALF_WIDTH_GRID, 13 + ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_POS},

    ////Epuration station
    {17, TABLE_WIDTH_GRID - 5 - ROBOT_HALF_WIDTH_GRID, 26, 5 + ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {17 - ROBOT_HALF_WIDTH_GRID, TABLE_WIDTH_GRID - 5, ROBOT_HALF_WIDTH_GRID, 5, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {17, TABLE_WIDTH_GRID - 5, ROBOT_HALF_WIDTH_GRID, 5, FORBIDDEN, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {43, TABLE_WIDTH_GRID - 5, ROBOT_HALF_WIDTH_GRID, 5, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {43, TABLE_WIDTH_GRID - 5, ROBOT_HALF_WIDTH_GRID, 0, FORBIDDEN, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},

    //Distributors
    {0, 16, 2 + ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {0, 16 - ROBOT_HALF_WIDTH_GRID, 2, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {0, 16 + 2, 2, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {0 + 1, 16 + 1, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},

    {TABLE_LENGTH_GRID - 2 - ROBOT_HALF_WIDTH_GRID, 16, 2 + ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {TABLE_LENGTH_GRID - 2, 16 - ROBOT_HALF_WIDTH_GRID, 2, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {TABLE_LENGTH_GRID - 2, 16 + 2, 2, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {TABLE_LENGTH_GRID - 1, 16 + 1, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},

    {11, TABLE_WIDTH_GRID - 2 - ROBOT_HALF_WIDTH_GRID, 2, 2 + ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {11 - ROBOT_HALF_WIDTH_GRID, TABLE_WIDTH_GRID - 2, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {11 + 2, TABLE_WIDTH_GRID - 2, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {11 + 1, TABLE_WIDTH_GRID - 1, ROBOT_HALF_WIDTH_GRID, 0, FORBIDDEN, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},

    {47, TABLE_WIDTH_GRID - 2 - ROBOT_HALF_WIDTH_GRID, 2, 2 + ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {47 - ROBOT_HALF_WIDTH_GRID, TABLE_WIDTH_GRID - 2, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {47 + 2, TABLE_WIDTH_GRID - 2, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    {47 + 1, TABLE_WIDTH_GRID - 1, ROBOT_HALF_WIDTH_GRID, 0, FORBIDDEN, CIRCLE, 0, COCOBOT_GAME_STATE_COLOR_ALL},
    
    //Cubes
    //Cube 0
    {17, 11, 2 + ROBOT_HALF_WIDTH_GRID, 4, GAME_ELEMENT, CIRCLE, 1, COCOBOT_GAME_STATE_COLOR_ALL},
    //Cube 1
    {43, 11, 2 + ROBOT_HALF_WIDTH_GRID, 4, GAME_ELEMENT, CIRCLE, 1, COCOBOT_GAME_STATE_COLOR_ALL},
    //Cube 2
    {6, 24, 2 + ROBOT_HALF_WIDTH_GRID, 4, GAME_ELEMENT, CIRCLE, 1, COCOBOT_GAME_STATE_COLOR_ALL},
    //Cube 3
    {54, 24, 2 + ROBOT_HALF_WIDTH_GRID, 4, GAME_ELEMENT, CIRCLE, 1, COCOBOT_GAME_STATE_COLOR_ALL},
    //Cube 4
    {22, 30, 2 + ROBOT_HALF_WIDTH_GRID, 4, GAME_ELEMENT, CIRCLE, 1, COCOBOT_GAME_STATE_COLOR_ALL},
    //Cube 5
    {38, 30, 2 + ROBOT_HALF_WIDTH_GRID, 4, GAME_ELEMENT, CIRCLE, 1, COCOBOT_GAME_STATE_COLOR_ALL},
    


    {0, 0, 0, 0, 0, 0, 0, 0}//Last line
};


void cocobot_pathfinder_conf_remove_game_element(gameElement_e element)
{
    switch (element)
    {
        case CUBE_CROSS_0:
            cocobot_pathfinder_remove_game_element(17, 11, 2); 
            break;
        case CUBE_CROSS_1:
            cocobot_pathfinder_remove_game_element(43, 11, 2); 
            break;
        case CUBE_CROSS_2:
            cocobot_pathfinder_remove_game_element(6, 24, 2); 
            break;
        case CUBE_CROSS_3:
            cocobot_pathfinder_remove_game_element(54, 24, 2); 
            break;
        case CUBE_CROSS_4:
            cocobot_pathfinder_remove_game_element(22, 30, 2); 
            break;
        case CUBE_CROSS_5:
            cocobot_pathfinder_remove_game_element(38, 30, 2); 
            break;
    }
}
