#ifndef COCOBOT_CONFIG_H
#define COCOBOT_CONFIG_H

#define COCOBOT_CONFIG_COM_CAN_MIN_ID 0
#define COCOBOT_CONFIG_COM_CAN_MAX_ID 128

#define COCOBOT_CONFIG_COM_RF_MIN_ID 0
#define COCOBOT_CONFIG_COM_RF_MAX_ID 128

#endif//COCOBOT_CONFIG_H
