MCUAL_VERSION = 0.1
MCUAL_URL = https://github.com/cocobot/mcual/archive/$(MCUAL_VERSION).tar.gz
MCUAL_ARCHIVE =$(MCUAL_FILE_PATH).tar.gz
MCUAL_GIT_UPSTREAM_URL = git@github.com:cocobot/mcual.git

#fake dependency to get autogenerated headers
MCUAL_AUTOGEN_INCLUDES=-I"$(CURDIR)"

MCUAL_DEPENDENCIES=system operating_systems mcual_autogen

# File path
ifeq ($(CONFIG_MCUAL_USE_GIT),y)
MCUAL_FILE_PATH=git
else
MCUAL_FILE_PATH=mcual-$(MCUAL_VERSION)
endif

# Include files
MCUAL_INCLUDE_PATH=$(MCUAL_FILE_PATH)/include/

MCUAL_SRC_FILES=$(MCUAL_FILE_PATH)/src/clock_arm.c \
								$(MCUAL_FILE_PATH)/src/gpio_arm.c	 \
								$(MCUAL_FILE_PATH)/src/usart_arm.c	

$(eval $(call pkg-generic,MCUAL))
