MCUAL_VERSION = 0.1
MCUAL_URL = https://github.com/cocobot/mcual/archive/$(MCUAL_VERSION).tar.gz
MCUAL_ARCHIVE =$(MCUAL_FILE_PATH).tar.gz
MCUAL_GIT_UPSTREAM_URL = git@github.com:cocobot/mcual.git

#fake dependency to get autogenerated headers
MCUAL_AUTOGEN_INCLUDES=-I"$(CURDIR)"
MCUAL_AUTOGEN_LOAD:

MCUAL_DEPENDENCIES=system operating_systems mcual_autogen

ifeq ($(CONFIG_AVR_CORE),y)
MCUAL_ARCH=avr
else
MCUAL_ARCH=arm
endif

# File path
ifeq ($(CONFIG_MCUAL_USE_GIT),y)
MCUAL_FILE_PATH=git
else
MCUAL_FILE_PATH=mcual-$(MCUAL_VERSION)
endif

# Include files
MCUAL_INCLUDE_PATH=$(MCUAL_FILE_PATH)/include/

MCUAL_TARGET_SRC_FILES=$(MCUAL_FILE_PATH)/src/$(MCUAL_ARCH)/clock.c \
								$(MCUAL_FILE_PATH)/src/$(MCUAL_ARCH)/gpio.c	 \
								$(MCUAL_FILE_PATH)/src/$(MCUAL_ARCH)/adc.c	 \
								$(MCUAL_FILE_PATH)/src/$(MCUAL_ARCH)/usart.c \
								$(MCUAL_FILE_PATH)/src/$(MCUAL_ARCH)/timer.c \
								$(MCUAL_FILE_PATH)/src/$(MCUAL_ARCH)/spi.c \
								$(MCUAL_FILE_PATH)/src/$(MCUAL_ARCH)/loader.c \
								$(MCUAL_FILE_PATH)/src/$(MCUAL_ARCH)/arch.c

MCUAL_SIM_SRC_FILES=$(MCUAL_FILE_PATH)/src/sim/clock.c \
								$(MCUAL_FILE_PATH)/src/sim/gpio.c	 \
								$(MCUAL_FILE_PATH)/src/sim/adc.c	 \
								$(MCUAL_FILE_PATH)/src/sim/usart.c \
								$(MCUAL_FILE_PATH)/src/sim/timer.c \
								$(MCUAL_FILE_PATH)/src/sim/spi.c \
								$(MCUAL_FILE_PATH)/src/sim/arch.c



$(eval $(call pkg-generic,MCUAL))
