/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/damien/prog/cocobot/ausbee-packages/libcocobot/dsdl/uavcan/cocobot/BrushlessConfig.uavcan
 */

#ifndef __UAVCAN_COCOBOT_BRUSHLESSCONFIG
#define __UAVCAN_COCOBOT_BRUSHLESSCONFIG

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
float32 kp
float32 ki
float32 imax
float32 max_speed_rpm
******************************************************************************/

/********************* DSDL signature source definition ***********************
uavcan.cocobot.BrushlessConfig
saturated float32 kp
saturated float32 ki
saturated float32 imax
saturated float32 max_speed_rpm
******************************************************************************/

#define UAVCAN_COCOBOT_BRUSHLESSCONFIG_NAME                "uavcan.cocobot.BrushlessConfig"
#define UAVCAN_COCOBOT_BRUSHLESSCONFIG_SIGNATURE           (0xFB33158EEDE6E517ULL)

#define UAVCAN_COCOBOT_BRUSHLESSCONFIG_MAX_SIZE            ((128 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    float      kp;                            // float32 Saturate
    float      ki;                            // float32 Saturate
    float      imax;                          // float32 Saturate
    float      max_speed_rpm;                 // float32 Saturate

} uavcan_cocobot_BrushlessConfig;

extern
uint32_t uavcan_cocobot_BrushlessConfig_encode(uavcan_cocobot_BrushlessConfig* source, void* msg_buf);

extern
int32_t uavcan_cocobot_BrushlessConfig_decode(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_cocobot_BrushlessConfig* dest, uint8_t** dyn_arr_buf);

extern
uint32_t uavcan_cocobot_BrushlessConfig_encode_internal(uavcan_cocobot_BrushlessConfig* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t uavcan_cocobot_BrushlessConfig_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_cocobot_BrushlessConfig* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __UAVCAN_COCOBOT_BRUSHLESSCONFIG