/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/damien/prog/ausbee-packages/libcocobot/dsdl/uavcan/cocobot/20001.GameState.uavcan
 */

#ifndef __UAVCAN_COCOBOT_GAMESTATE
#define __UAVCAN_COCOBOT_GAMESTATE

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
#
# battery in mV
uint16 battery

# time in s
uint16 time

# score
uint16 score

# 1 if positive, 0 if negative
bool color
******************************************************************************/

/********************* DSDL signature source definition ***********************
uavcan.cocobot.GameState
saturated uint16 battery
saturated uint16 time
saturated uint16 score
saturated bool color
******************************************************************************/

#define UAVCAN_COCOBOT_GAMESTATE_ID                        20001
#define UAVCAN_COCOBOT_GAMESTATE_NAME                      "uavcan.cocobot.GameState"
#define UAVCAN_COCOBOT_GAMESTATE_SIGNATURE                 (0x6D587713AA5AC19FULL)

#define UAVCAN_COCOBOT_GAMESTATE_MAX_SIZE                  ((49 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    uint16_t   battery;                       // bit len 16
    uint16_t   time;                          // bit len 16
    uint16_t   score;                         // bit len 16
    bool       color;                         // bit len 1

} uavcan_cocobot_GameState;

extern
uint32_t uavcan_cocobot_GameState_encode(uavcan_cocobot_GameState* source, void* msg_buf);

extern
int32_t uavcan_cocobot_GameState_decode(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_cocobot_GameState* dest, uint8_t** dyn_arr_buf);

extern
uint32_t uavcan_cocobot_GameState_encode_internal(uavcan_cocobot_GameState* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t uavcan_cocobot_GameState_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_cocobot_GameState* dest, uint8_t** dyn_arr_buf, int32_t offset);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __UAVCAN_COCOBOT_GAMESTATE