/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/damien/prog/cocobot/ausbee-packages/libcocobot/dsdl/uavcan/cocobot/201.RequestBrushlessSpeed.uavcan
 */

#ifndef __UAVCAN_COCOBOT_REQUESTBRUSHLESSSPEED
#define __UAVCAN_COCOBOT_REQUESTBRUSHLESSSPEED

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
---

float32 rpm
******************************************************************************/

/********************* DSDL signature source definition ***********************
uavcan.cocobot.RequestBrushlessSpeed
---
saturated float32 rpm
******************************************************************************/

#define UAVCAN_COCOBOT_REQUESTBRUSHLESSSPEED_ID            201
#define UAVCAN_COCOBOT_REQUESTBRUSHLESSSPEED_NAME          "uavcan.cocobot.RequestBrushlessSpeed"
#define UAVCAN_COCOBOT_REQUESTBRUSHLESSSPEED_SIGNATURE     (0x7EA7DF665B2231F8ULL)

#define UAVCAN_COCOBOT_REQUESTBRUSHLESSSPEED_REQUEST_MAX_SIZE ((0 + 7)/8)

typedef struct
{
    uint8_t empty;
} uavcan_cocobot_RequestBrushlessSpeedRequest;

extern
uint32_t uavcan_cocobot_RequestBrushlessSpeedRequest_encode(uavcan_cocobot_RequestBrushlessSpeedRequest* source, void* msg_buf);

extern
int32_t uavcan_cocobot_RequestBrushlessSpeedRequest_decode(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_cocobot_RequestBrushlessSpeedRequest* dest, uint8_t** dyn_arr_buf);

extern
uint32_t uavcan_cocobot_RequestBrushlessSpeedRequest_encode_internal(uavcan_cocobot_RequestBrushlessSpeedRequest* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t uavcan_cocobot_RequestBrushlessSpeedRequest_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_cocobot_RequestBrushlessSpeedRequest* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#define UAVCAN_COCOBOT_REQUESTBRUSHLESSSPEED_RESPONSE_MAX_SIZE ((32 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    float      rpm;                           // float32 Saturate

} uavcan_cocobot_RequestBrushlessSpeedResponse;

extern
uint32_t uavcan_cocobot_RequestBrushlessSpeedResponse_encode(uavcan_cocobot_RequestBrushlessSpeedResponse* source, void* msg_buf);

extern
int32_t uavcan_cocobot_RequestBrushlessSpeedResponse_decode(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_cocobot_RequestBrushlessSpeedResponse* dest, uint8_t** dyn_arr_buf);

extern
uint32_t uavcan_cocobot_RequestBrushlessSpeedResponse_encode_internal(uavcan_cocobot_RequestBrushlessSpeedResponse* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t uavcan_cocobot_RequestBrushlessSpeedResponse_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_cocobot_RequestBrushlessSpeedResponse* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __UAVCAN_COCOBOT_REQUESTBRUSHLESSSPEED