/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/vfaure/Eurobot2019/ausbee-packages/libcocobot/dsdl/uavcan/cocobot/20001.SetMotorSpeed.uavcan
 */

#ifndef __UAVCAN_COCOBOT_SETMOTORSPEED
#define __UAVCAN_COCOBOT_SETMOTORSPEED

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
bool enable
float32 rpm
******************************************************************************/

/********************* DSDL signature source definition ***********************
uavcan.cocobot.SetMotorSpeed
saturated bool enable
saturated float32 rpm
******************************************************************************/

#define UAVCAN_COCOBOT_SETMOTORSPEED_ID                    20001
#define UAVCAN_COCOBOT_SETMOTORSPEED_NAME                  "uavcan.cocobot.SetMotorSpeed"
#define UAVCAN_COCOBOT_SETMOTORSPEED_SIGNATURE             (0x7C528E89396EF1A7ULL)

#define UAVCAN_COCOBOT_SETMOTORSPEED_MAX_SIZE              ((33 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    bool       enable;                        // bit len 1
    float      rpm;                           // float32 Saturate

} uavcan_cocobot_SetMotorSpeed;

extern
uint32_t uavcan_cocobot_SetMotorSpeed_encode(uavcan_cocobot_SetMotorSpeed* source, void* msg_buf);

extern
int32_t uavcan_cocobot_SetMotorSpeed_decode(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_cocobot_SetMotorSpeed* dest, uint8_t** dyn_arr_buf);

extern
uint32_t uavcan_cocobot_SetMotorSpeed_encode_internal(uavcan_cocobot_SetMotorSpeed* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t uavcan_cocobot_SetMotorSpeed_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_cocobot_SetMotorSpeed* dest, uint8_t** dyn_arr_buf, int32_t offset);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __UAVCAN_COCOBOT_SETMOTORSPEED