
//Remove definitions from make menuconfig
#undef CONFIG_LIBCOCOBOT_POSITION_TICK_PER_180DEG
#undef CONFIG_LIBCOCOBOT_POSITION_TICK_PER_METER
#undef CONFIG_LIBCOCOBOT_DIST_RAMP_MAX_SPEED
#undef CONFIG_LIBCOCOBOT_DIST_RAMP_MAX_ACCEL
#undef CONFIG_LIBCOCOBOT_ANGU_RAMP_MAX_SPEED
#undef CONFIG_LIBCOCOBOT_ANGU_RAMP_MAX_ACCEL
#undef CONFIG_LIBCOCOBOT_DIST_PID_KP 
#undef CONFIG_LIBCOCOBOT_DIST_PID_KD 
#undef CONFIG_LIBCOCOBOT_DIST_PID_KI 
#undef CONFIG_LIBCOCOBOT_DIST_PID_MAX_INTEGRAL 
#undef CONFIG_LIBCOCOBOT_DIST_PID_MAX_ERROR_FOR_INTEGRATION 
#undef CONFIG_LIBCOCOBOT_ANGU_PID_KP 
#undef CONFIG_LIBCOCOBOT_ANGU_PID_KD 
#undef CONFIG_LIBCOCOBOT_ANGU_PID_KI 
#undef CONFIG_LIBCOCOBOT_ANGU_PID_MAX_INTEGRAL 
#undef CONFIG_LIBCOCOBOT_ANGU_PID_MAX_ERROR_FOR_INTEGRATION 


//Add custom values
#define CONFIG_LIBCOCOBOT_POSITION_TICK_PER_180DEG  21210
#define CONFIG_LIBCOCOBOT_POSITION_TICK_PER_METER   58860

#define CONFIG_LIBCOCOBOT_DIST_RAMP_MAX_SPEED       100
#define CONFIG_LIBCOCOBOT_DIST_RAMP_MAX_ACCEL       100
#define CONFIG_LIBCOCOBOT_ANGU_RAMP_MAX_SPEED       100
#define CONFIG_LIBCOCOBOT_ANGU_RAMP_MAX_ACCEL       100

#define CONFIG_LIBCOCOBOT_DIST_PID_KP               1
#define CONFIG_LIBCOCOBOT_DIST_PID_KD               0
#define CONFIG_LIBCOCOBOT_DIST_PID_KI               0
#define CONFIG_LIBCOCOBOT_DIST_PID_MAX_INTEGRAL     0
#define CONFIG_LIBCOCOBOT_DIST_PID_MAX_ERROR_FOR_INTEGRATION  0 

#define CONFIG_LIBCOCOBOT_ANGU_PID_KP               0 
#define CONFIG_LIBCOCOBOT_ANGU_PID_KD               0
#define CONFIG_LIBCOCOBOT_ANGU_PID_KI               0
#define CONFIG_LIBCOCOBOT_ANGU_PID_MAX_INTEGRAL     0 
#define CONFIG_LIBCOCOBOT_ANGU_PID_MAX_ERROR_FOR_INTEGRATION  0 
