#ifndef COCOBOT_CONFIG_H
#define COCOBOT_CONFIG_H

#define COCOBOT_CAN_MOTOR
#define COCOBOT_COM_NODE_ID 10
#define COCOBOT_RIGHT_MOTOR_NODE_ID 13
#define COCOBOT_LEFT_MOTOR_NODE_ID 12
#define COCOBOT_LIDAR_NODE_ID 14
#define COCOBOT_MECA_NODE_ID 15

#endif//COCOBOT_CONFIG_H
