#ifndef COCOBOT_CONFIG_H
#define COCOBOT_CONFIG_H

#define COCOBOT_ROBOT_ID 1 //(0 RP, 1 PMI)

#define COCOBOT_GS_UD_SHELL_CONFIGURATION 0

#define COCOBOT_INVERT_LEFT_MOTOR
//#define COCOBOT_INVERT_RIGHT_MOTOR
#define COCOBOT_L298

#define COCOBOT_LOW_BAT_THRESHOLD 14800

#define COCOBOT_ROBOT_DEPTH (145 / 2)

#define COCOBOT_SHIFTERS_OUT_NUMBER 3

#define COCOBOT_INVERT_ENCODERS

#endif//COCOBOT_CONFIG_H
