#include "cocobot_pathfinder_config.h"
#include "cocobot.h"


cocobot_pathfinder_table_init_s initTable [] = 
{
    //Walls
    {0, 0, TABLE_LENGTH_GRID, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE},
    {0, TABLE_WIDTH_GRID - ROBOT_HALF_WIDTH_GRID, TABLE_LENGTH_GRID, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE},
    {0, 0, ROBOT_HALF_WIDTH_GRID, TABLE_WIDTH_GRID, FORBIDDEN, RECTANGLE},
    {TABLE_LENGTH_GRID - ROBOT_HALF_WIDTH_GRID, 0, ROBOT_HALF_WIDTH_GRID, TABLE_WIDTH_GRID, FORBIDDEN, RECTANGLE},

    //Epuration station
    {17, TABLE_WIDTH_GRID - 5 - ROBOT_HALF_WIDTH_GRID, 26, 5 + ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE},
    {17 - ROBOT_HALF_WIDTH_GRID, TABLE_WIDTH_GRID - 5, ROBOT_HALF_WIDTH_GRID, 5, FORBIDDEN, RECTANGLE},
    {17, TABLE_WIDTH_GRID - 5, ROBOT_HALF_WIDTH_GRID, 5, FORBIDDEN, CIRCLE},
    {43, TABLE_WIDTH_GRID - 5, ROBOT_HALF_WIDTH_GRID, 5, FORBIDDEN, RECTANGLE},
    {43, TABLE_WIDTH_GRID - 5, ROBOT_HALF_WIDTH_GRID, 0, FORBIDDEN, CIRCLE},

    //Distributors
    {0, 16, 2 + ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE},
    {0, 16 - ROBOT_HALF_WIDTH_GRID, 2, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE},
    {0, 16 + 2, 2, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE},
    {0 + 1, 16 + 1, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, CIRCLE},

    {TABLE_LENGTH_GRID - 2 - ROBOT_HALF_WIDTH_GRID, 16, 2 + ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE},
    {TABLE_LENGTH_GRID - 2, 16 - ROBOT_HALF_WIDTH_GRID, 2, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE},
    {TABLE_LENGTH_GRID - 2, 16 + 2, 2, ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE},
    {TABLE_LENGTH_GRID - 1, 16 + 1, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, CIRCLE},

    {11, TABLE_WIDTH_GRID - 2 - ROBOT_HALF_WIDTH_GRID, 2, 2 + ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE},
    {11 - ROBOT_HALF_WIDTH_GRID, TABLE_WIDTH_GRID - 2, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE},
    {11 + 2, TABLE_WIDTH_GRID - 2, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE},
    {11 + 1, TABLE_WIDTH_GRID - 1, ROBOT_HALF_WIDTH_GRID, 0, FORBIDDEN, CIRCLE},

    {47, TABLE_WIDTH_GRID - 2 - ROBOT_HALF_WIDTH_GRID, 2, 2 + ROBOT_HALF_WIDTH_GRID, FORBIDDEN, RECTANGLE},
    {47 - ROBOT_HALF_WIDTH_GRID, TABLE_WIDTH_GRID - 2, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE},
    {47 + 2, TABLE_WIDTH_GRID - 2, ROBOT_HALF_WIDTH_GRID, 2, FORBIDDEN, RECTANGLE},
    {47 + 1, TABLE_WIDTH_GRID - 1, ROBOT_HALF_WIDTH_GRID, 0, FORBIDDEN, CIRCLE},
    
    

    //{30, 20, 5, 0, FORBIDDEN, CIRCLE},
    {0, 0, 0, 0, 0, 0}//Last line
};
