#ifndef COCOBOT_CONFIG_H
#define COCOBOT_CONFIG_H

#define COCOBOT_ROBOT_ID 0 //(0 RP, 1 PMI)

#define COCOBOT_GS_UD_SHELL_CONFIGURATION 0
#define COCOBOT_LMD18200T

#define COCOBOT_LOW_BAT_THRESHOLD 18000

//#define COCOBOT_INVERT_LEFT_MOTOR

#define COCOBOT_ROBOT_DEPTH (220 / 2)

#endif//COCOBOT_CONFIG_H
